[workspace]
authors = ["Nicolasmelo16 <nicolasmeloreis@hotmail.com>"]
channels = ["conda-forge"]
name = "Calculo_Numerico"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
notebook = ">=7.4.7,<8"
numpy = ">=2.3.3,<3"
pandas = ">=2.3.2,<3"
matplotlib = ">=3.10.6,<4"
jupyter = ">=1.1.1,<2"
python = ">=3.13.7,<3.14"
git = ">=2.51.0,<3"
